"""<new columns in competitions>

Revision ID: 01c7f76566b1
Revises: 94166c2869ff
Create Date: 2023-07-28 13:56:26.872379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c7f76566b1'
down_revision = '94166c2869ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('objective', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('scoring', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('competition_tasks', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('safety_measures', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_column('safety_measures')
        batch_op.drop_column('competition_tasks')
        batch_op.drop_column('scoring')
        batch_op.drop_column('objective')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
