"""<your message>

Revision ID: 24f6b6d9c813
Revises: 
Create Date: 2023-08-02 14:08:22.186922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f6b6d9c813'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_of_hobby', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('profileImg', sa.String(), nullable=True),
    sa.Column('bannerImg', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('scoring', sa.String(), nullable=True),
    sa.Column('cost_of_entry', sa.Integer(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('competition_tasks', sa.String(), nullable=True),
    sa.Column('safety_measures', sa.String(), nullable=True),
    sa.Column('prize1', sa.String(), nullable=True),
    sa.Column('prize2', sa.String(), nullable=True),
    sa.Column('prize3', sa.String(), nullable=True),
    sa.Column('prize4', sa.String(), nullable=True),
    sa.Column('prize5', sa.String(), nullable=True),
    sa.Column('prize6', sa.String(), nullable=True),
    sa.Column('prize7', sa.String(), nullable=True),
    sa.Column('prize8', sa.String(), nullable=True),
    sa.Column('registration_schedule', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_competitions_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expertise', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hobby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobbies.id'], name=op.f('fk_user_hobbies_hobby_id_hobbies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_hobbies_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_entries_competition_id_competitions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_results_competition_id_competitions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_results_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('entries')
    op.drop_table('user_hobbies')
    op.drop_table('competitions')
    op.drop_table('users')
    op.drop_table('hobbies')
    # ### end Alembic commands ###
