"""<trial 6>

Revision ID: 9fbd3416ebbc
Revises: 
Create Date: 2023-07-28 15:35:34.286715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fbd3416ebbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('scoring', sa.String(), nullable=True),
    sa.Column('cost_of_entry', sa.Integer(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('requirements', sa.String(), nullable=True),
    sa.Column('competition_tasks', sa.String(), nullable=True),
    sa.Column('safety_measures', sa.String(), nullable=True),
    sa.Column('prize1', sa.String(), nullable=True),
    sa.Column('prize2', sa.String(), nullable=True),
    sa.Column('prize3', sa.String(), nullable=True),
    sa.Column('prize4', sa.String(), nullable=True),
    sa.Column('prize5', sa.String(), nullable=True),
    sa.Column('prize6', sa.String(), nullable=True),
    sa.Column('prize7', sa.String(), nullable=True),
    sa.Column('prize8', sa.String(), nullable=True),
    sa.Column('registration_schedule', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hobby', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('profileImg', sa.String(), nullable=True),
    sa.Column('bannerImg', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expertise', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hobby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobbies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_hobbies')
    op.drop_table('results')
    op.drop_table('entries')
    op.drop_table('users')
    op.drop_table('hobbies')
    op.drop_table('competitions')
    # ### end Alembic commands ###
